#!/usr/bin/env bash
# script to install nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sudo service nginx restart > /dev/null 2>&1 || sudo /etc/init.d/nginx restart > /dev/null 2>&1
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
