#!/usr/bin/env bash
# configures a brand new Ubuntu machine with custom header contained
# in the HTTP response
apt-get -y update
apt-get -y install nginx
sudo sed -i "47i \\\tadd_header X-Served-By $HOSTNAME;\n" /etc/nginx/sites-available/default
service nginx restart
