#!/usr/bin/env bash
# script that configures a High Availability Proxy
sudo apt update
sudo apt install haproxy -y

sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
echo -e "\nfrontend localnodes\n\tbind *:80\n\tmode http\n\tdefault_backend nodes\n\nbackend nodes\n\tbalance roundrobin\n\tserver 232862-web-01 100.26.234.25:80 check\n\tserver 232862-web-02 100.26.235.62:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
service haproxy restart
