#!/usr/bin/env bash
# Display multiples of 3 and 5 between 1 and 100
i=1
while [ $i -lt 100 ]; do
      if [ $((i % 3)) == 0 ] && [ $((i % 5)) == 0 ]; then
         echo "FizzBuzz"
      elif [ $((i % 5)) == 0 ]; then
         echo "Buzz"
      elif [ $((i % 3)) == 0 ]; then
         echo "Fizz"
      else
         echo $i
      fi
      i=$(( i + 1))
done
