#!/usr/bin/env bash
# Use while loop to display strings
i=0
while [ $i -lt 11 ]; do
      if [ $i -eq 9 ]; then
        echo "Hi"
      else
        echo "Best School"
      fi
      i=$(( i + 1))
done
