#!/usr/bin/env bash
# Configuring ufw firewall to restrict all incoming traffic
# Don't restrict TCP in port: 22, 443 and 80


sudo apt-get install ufw
sudo sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
sudo ufw disable
sudo ufw enable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw reload
sudo ufw status
